### ISSUE TITLE
Docker file of halconsole/hal-wildfly-nightly doesn't seems to be published on github

### ISSUE THREAD

**Issue by marekkopecky** [hal/testsuite.next#115]
Docker file of halconsole/hal-wildfly-nightly doesn't seems to be published on github

https://hub.docker.com/r/halconsole/hal-wildfly-nightly/tags/

cc @spriadka @honza-kasik

**Comment by spriadka** [comment]
The Dockerfile is present in the console repository (https://github.com/hal/console/tree/develop/docker)

**Comment by marekkopecky** [comment]
@spriadka This doesn't seems to be correct. According to the [readme](https://github.com/hal/testsuite.next/blob/master/README.md), [halconsole/hal-wildfly-nightly](https://hub.docker.com/r/halconsole/hal-wildfly-nightly) is based on `jboss/wildfly`. This corresponds with  comparison of `docker inspect halconsole/hal-wildfly-nightly` and `docker inspect jboss/wildfly`.

[Dockerfile from console repository](https://github.com/hal/console/blob/develop/docker/src/main/docker/hal/Dockerfile) is based on `jboss/base-jdk:11`, not on `jboss/wildfly` ...

**Comment by honza-kasik** [comment]
@marekkopecky So this is the history:
* `hal-wildfly-nightly` image have been being build when console was built with `docker` profile
* 3 docker images total were built
* In revision [cd34a64951fb6cb3baaebc0c9e9266bd7669c3cc](https://github.com/hal/console/commit/cd34a64951fb6cb3baaebc0c9e9266bd7669c3cc#diff-0623e74c32b929ec031a705ec7de0c51) the generation code was removed.

@hpehl Why was the code removed?

**Comment by hpehl** [comment]
@honza-kasik @marekkopecky @spriadka Sorry for the broken build and missing docker images. The images have been removed by accident. I'm about to restore them. I'll comment here if everything is up and running again.

**Comment by hpehl** [comment]
I've restored the missing maven-docker setup https://github.com/hal/console/commit/607053f4395bb1f3d26ba758f9b566bd6527ef5e and pushed the docker images: https://cloud.docker.com/repository/list?namespace=halconsole.

**Comment by marekkopecky** [comment]
@hpehl Thank you. I'm comparing [hal-wildfly](https://hub.docker.com/r/halconsole/hal-wildfly-nightly) and [wildfly](https://hub.docker.com/r/jboss/wildfly). [Wildfly](https://hub.docker.com/r/jboss/wildfly) contains link to github sources in `Source Repository` section. [Hal-wildfly](https://hub.docker.com/r/halconsole/hal-wildfly-nightly) not. Can you consider to add `Source Repository` section also to [Hal-wildfly](https://hub.docker.com/r/halconsole/hal-wildfly-nightly) docker page?

**Comment by hpehl** [comment]
Setup source repo and automatic builds for [`halconsole/hal`](https://cloud.docker.com/repository/docker/halconsole/hal), [`halconsole/hal-wildfly`](https://cloud.docker.com/repository/docker/halconsole/hal-wildfly) and [`halconsole/hal-wildfly-nightly`](https://cloud.docker.com/repository/docker/halconsole/hal-wildfly-nightly)

**Comment by marekkopecky** [comment]
@hpehl Thank you. In my PoV, this issue is solved now, so I close it  now ...
