### ISSUE TITLE
Compilation error: cannot find symbol [ERROR] symbol: variable DISTRIBUTABLE_WEB

### ISSUE THREAD

**Issue by mcharaya** [hal/testsuite.next#134]
Compilation error on running mvn clean install -Djboss.dist=/

 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project hal-testsuite-common: Compilation failure
[ERROR] /testsuite.next/common/src/main/java/org/jboss/hal/testsuite/page/configuration/DistributableWebPage.java:[32,18] cannot find symbol
[ERROR]   symbol:   variable DISTRIBUTABLE_WEB
[ERROR]   location: interface org.jboss.hal.meta.token.NameTokens

This variable is not found in jar downloaded from jboss-snapshots-repository: https://repository.jboss.org/nexus/content/repositories/snapshots/org/jboss/hal/hal-testsuite-resources/3.2.1-SNAPSHOT/hal-testsuite-resources-3.2.1-20190806.100500-1.jar

cc @hpehl

**Comment by hpehl** [comment]
Thanks for reporting @mcharaya. Should be fixed by https://github.com/hal/testsuite.next/commit/ff1ac593420b402fdd570113b3fdf5bcaec46b7c. Could you please verify?

**Comment by mcharaya** [comment]
Thanks for the fix @hpehl . It is working now.
