### ISSUE TITLE
Maven JAR plugin is reporting warning(s)

### ISSUE THREAD

**Issue by spriadka** [hal/testsuite.next#16]
In the current state of the project, the ``default-jar`` goal of the ``maven-jar-plugin`` is reporting this error: ``[WARNING] JAR will be empty - no content was marked for inclusion!`` when building the  ``test`` and its submodules. As we want to keep the Maven build logs as warning-less as possible, such behavior is undesired.

**Comment by hpehl** [comment]
Fixed with #17
